collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.435033
  brandStrength: 0.4392557
  lightness: 0.2207146
  brandColors:
    - '#FFFFFF'
    - '#B35CE1'
    - '#E15C89'
    - '#DEA93F'
    - '#5B928F'
  rhythmicContrast: 0.1491745
typography_spectrum: 0.5163305
layout_spectrum: 0.5212766
name: Young Living Essential Oils
