layout_spectrum: 0.7816617
typography_spectrum: 0.5163305
color:
  saturation: 0.435033
  lightness: 0.2207146
  brandStrength: 0.4392557
  rhythmicContrast: 0.1491745
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: Young Living Essential Oils
